### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by DataWorm** [robweber/octoprint-java-lib#9] opened 2017-08-08 22:46 UTC
Hey, I'm back! And also just found another bug:

```
public Long getEstimatedPrintTime(){
	return new Long(m_job.get("estimatedPrintTime").toString());
}
```
When there is no print job assigned, estimatedPrintTime is set to null and therefore calling toString() results in a NPE. Of course that issue is probably existent on other places too.

P.S. I guess I can work a bit on the exceptions in 1-2 weeks.

**Comment by robweber** [comment] 2017-08-09 17:57
Good catch. Thinking about it there are 2 different cases. Either a) no file loaded at all or b) a file loaded but is not yet printing. Both return some values, and some null values. I have a partial solution working, just going to test. Should be fixed quickly. 

Sounds good on the exceptions. I updated the JSON library and merged it. It has some better primitive handling than the old one.

**Closed as completed** 2017-08-09 19:08 UTC

**Comment by DataWorm** [comment] 2017-08-13 22:08
Sorry mate, but that library really seems to be a pain in the ass! :-D

public Double volume(){
	if(!this.m_json.containsKey("volume")) {
		return null;
	}
	return this.m_json.getDouble("volume");
}

This was one of my methods that you updated with the new framework. It checks if the key is present and then retrieves the double value. But we also got the situation that they key is present but value is set to null. One might expect the method getDouble would return a null value under these circumstances but instead it seems to throw an NPE:

```
java.lang.NullPointerException: null
	at org.json.simple.JsonObject.getDouble(JsonObject.java:213)
	at org.octoprint.api.model.OctoPrintJob$FilamentDetails.volume(OctoPrintJob.java:201)
	at de.hendrikmotza.iolite.driver.OctoPrintDeviceDataPointFactory.updateJobValues(OctoPrintDeviceDataPointFactory.java:205)
	at ...
```

**Comment by DataWorm** [comment] 2017-08-13 23:34
Made a pull request for the mentioned issue, but didn't check if this also appears somewhere else.

**Comment by robweber** [comment] 2017-08-14 13:31
I agree, it's becoming more of an issue than I'd like. You could point a lot of fingers here at the root cause; personally I'd rather the REST API just not return values instead of returning them null. On the other hand the library should handle these better. I was hoping by updating it they would account for NP type checks before doing the Long or Double cast. 

I can see two long term fixes here. The first being just patching the simple-json lib. I took a look at their code and it may not take much, it seems reasonably well organized. I might attempt this. The other would be to pull it out and use Jackson.

**Comment by DataWorm** [comment] 2017-08-14 18:41
If you can improve their implementation and they merge it back it would be an improvement for the whole community of that json library. Also it might have a lower footprint. Jackson on the other side already makes it easy to work with null values and conversion. And you can also define mappings to pojos which might be useful for this use-case. But as usual I'm fine with whatever you decide.

**Comment by robweber** [comment] 2017-10-03 13:10
Just to bring this full circle even though the issue is closed. The maintainer of the json-simple library made some changes to their recent version. I'll test it out in a new branch and see if it helps with these issues. I started to port things over to Jackson at one point a few weeks ago but hit some snags and haven't revisited. Might just go that route in the future.

**Comment by DataWorm** [comment] 2017-10-03 13:13
Yeah okay, just tell me if you need help at some point!
